graylog support
stephan-strate/grav-plugin-logger-channels pull request #2
Opened 2021-07-09 00:55 UTC by drzraf

2021-07-09 14:44 UTC, stephan-strate commented
I will give it a test in the next days. It will take some time, because I need to setup a graylog instance.
Also, you will need to add `graylog2/gelf-php` as dependency as I stated in https://github.com/stephan-strate/grav-plugin-logger-channels/pull/1#issuecomment-877237766.

2021-07-27 18:32 UTC, stephan-strate commented
I know it feels weird, but you actually need to add the vendor files to make this work. Grav installs the source itself.

Here are some examples:

- https://github.com/getgrav/grav-plugin-admin
- https://github.com/getgrav/grav-plugin-email

2021-10-14 13:32 UTC, drzraf commented
ping?

2021-10-14 17:38 UTC, stephan-strate commented
Sorry for letting you wait so long. This pull request got lost in my pile of work.
Could you provide me some instructions on how to test this properly? I am not familiar with graylog and therefore have no access to a running instance.

2021-10-20 18:17 UTC, drzraf commented
I use OVH hosted one. It's really cheap and work out of the box.

2021-10-30 14:35 UTC, stephan-strate requested changes
Looks good to me so far. One small change and this is done :)

2021-10-30 14:35 UTC, stephan-strate commented on classes/Handlers/GraylogHandler.php
> +        $this->handler = new GelfHandler($publisher);
We need the log level to be configurable. Have a look at eg. the TelegramHandler.

2021-11-08 19:11 UTC, merged